/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Keys API
 * Read access to pull request data.
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from "hono/factory";

import { ListPullRequestsContext } from "../generated/api.context";
import { zValidator } from "../generated/api.validator";
import { ListPullRequestsQueryParams, ListPullRequestsResponse } from "../generated/api.zod";
import { pullRequests } from "../stub-data";

const factory = createFactory();
export const listPullRequestsHandlers = factory.createHandlers(
  zValidator("query", ListPullRequestsQueryParams),
  zValidator("response", ListPullRequestsResponse),
  async (c: ListPullRequestsContext) => {
    const { cursor, limit = 20 } = c.req.valid("query");

    // The cursor is opaque to callers; here it is just an offset into the
    // stub list. Replace with a real GitHub-backed lookup.
    const offset = cursor ? Number(cursor) : 0;
    const items = pullRequests.slice(offset, offset + limit);
    const next = offset + items.length;

    return c.json({
      items,
      nextCursor: next < pullRequests.length ? String(next) : null,
    });
  },
);
